repos:
- repo: https://github.com/python/black
  rev: 22.3.0
  hooks:
  - id: black
    exclude: docopt.py
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-bugbear==20.1.2; python_version >= "3.5"']
- repo: https://github.com/asottile/blacken-docs
  rev: v1.8.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]
