trigger:
  branches:
    include: [dev, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

variables:
  CI: "true"

jobs:
- template: job--python-tox.yml@sloria
  parameters:
    toxenvs: [
      lint,

      py36-ipython5,
      py36-ipython6,
      py36-ipython7,

      py37-ipython6,
      py37-ipython7,

      py38-ipython7,
      py38-ipython8,

      py39-ipython7,
      py39-ipython8,

      py310-ipython7,
      py310-ipython8
    ]
    os: linux
- template: job--pypi-release.yml@sloria
  parameters:
    dependsOn:
      - tox_linux
